app_color = "magenta"
collapse_unfocused_tabs = false
show_key_hints = true
# Whether to open prompts upon project/task creation. False by default as this might be annoying
[always_open]
priority = false
difficulty = false
due_date = false

# When set to true, the due date will be automatically set based on priority (the numbers indicate how many days after today the task is due)
# This will not override the due date you set manually
[default_due_dates]
enable = false
high = 2
medium = 7
low = 30

# Column config. I personally use columns Idea Doing Waiting Done Won't do but this is the standard
[[column]]
name = "Backlog"
color = "red"
tab = 0

[[column]]
name = "Doing"
color = "yellow"
tab = 0

[[column]]
name = "Review"
color = "green"
tab = 0

[[column]]
name = "Done"
color = "blue"
tab = 1
# This option will exclude the tasks in due tasks list
# Multiple columns can have this option
done_column = true
